project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: javascript.qmd
        text: Javascript

format:
  html:
    self-contained: true
    theme: cosmo
    css: styles.css
    toc: true



